hibernate.connection.url=${POSTGRES_DB:jdbc:postgresql://localhost:5432/game}
hibernate.connection.username=${POSTGRES_USER:postgres}
hibernate.connection.password=${POSTGRES_PASSWORD:postgres}
hibernate.connection.driver_class=org.postgresql.Driver

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hibernate.ddl-auto=validate
hibernate.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect